<a href="https://colab.research.google.com/github/M-Sravanthi/DLExercise1/blob/main/00_pytorchFundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is zero to Mastery Pytorch course

Resource notebook - https://www.learnpytorch.io/00_pytorch_fundamentals/                   
Youtube: https://www.youtube.com/watch?v=Z_ikDlimN6A by Daniel Bourke

Questions: https://github.com/mrdbourke/pytorch-deep-learning/discussions/categories/q-a

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


It means cuda version 124 that this pytorch works on. CUDA provides pytorch.

## Introduction to tensors
### Creating tensors

Pytorch tensor - https://docs.pytorch.org/docs/stable/tensors.html

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Get tensor back as python int
scalar.item()

7

In [ ]:
#Vector - it magnitude and direction
vector = torch.tensor([9,9])
vector

tensor([9, 9])

In [ ]:
vector.ndim

1

In [ ]:
vector.size()

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[9,9],
                      [6,6]])
MATRIX.ndim
MATRIX.size()

torch.Size([2, 2])

In [ ]:
MATRIX[1]

tensor([6, 6])

In [ ]:
MATRIX[0]

tensor([9, 9])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.size()

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR2 = torch.tensor([[1, 2, 3]])
TENSOR2

tensor([[1, 2, 3]])

In [ ]:
TENSOR2.ndim

2

In [ ]:
TENSOR2.size()

torch.Size([1, 3])

In [ ]:
TENSOR2[0]

tensor([1, 2, 3])

### Random Tensors

Why random tensors?
Random tensors are importatnt because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update and so on == neural network

https://docs.pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(2,2,3)
random_tensor

tensor([[[0.8232, 0.6492, 0.0325],
         [0.9348, 0.9302, 0.5032]],

        [[0.9859, 0.2158, 0.6390],
         [0.1826, 0.5316, 0.4664]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, clour channels (RGB
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###Zeros and ones

In [ ]:
# Create a tensor of all zeros

zeros = torch.zeros(2,2,3)
zeros

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
zeros*random_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
#Create a tensor of ones

ones= torch.ones(2,2,3)
ones

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
ones.dtype

torch.float32

##Creating a range of tensors and tensors-like

In [ ]:
one_to_ten = torch.arange(0,11) #- arange works like [start,end)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
even = torch.arange(0,11,step=2)
even

tensor([ 0,  2,  4,  6,  8, 10])

In [ ]:
#Creating tensors-like

like_one_to_ten = torch.zeros_like(input=one_to_ten)
like_one_to_ten

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
like_even = torch.zeros_like(input=even)
like_even

tensor([0, 0, 0, 0, 0, 0])

### Tensor datatypes

Note: Tensor datatypes is one the 3 big errors one runs into with pytorch and deep learning
1. Tensors arer not right datatype
2. Tensors are not right shape
3. Tensors are not on the right device

In [ ]:
#Float 32

float32 = torch.tensor([3.0,6.0,9.0],dtype=None)
print(float32, "dtype =", float32.dtype)

#NOTE
float32 = torch.tensor([3.0,6.0,9.0],dtype=None, #datatype - float 32 or float 16
                                    device = None, # = cuda or gpu etc - all tensors should be in the same device to avoid errors
                                    requires_grad=False) #whether or not to track gradients with this operations
float32

tensor([3., 6., 9.]) dtype = torch.float32


tensor([3., 6., 9.])

In [ ]:
float16 = float32.type(torch.float16)
float16

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float16*float32

tensor([ 9., 36., 81.])

In [ ]:
int64 = torch.randint(3, 5, (3,)) #randint default is int64
int64, int64.dtype

(tensor([3, 4, 4]), torch.int64)

In [ ]:
int64*float16

tensor([ 9., 24., 36.], dtype=torch.float16)

### Getting information from tensors

Tensors are not right datatype = tensor.dtype
Tensors are not right shape = tensor.size/tensor.shape
Tensors are not on the right device = tensor.device

In [ ]:
#Create a tensor

some_t = torch.rand(3,4)
some_t

tensor([[0.4514, 0.9443, 0.1472, 0.3190],
        [0.8112, 0.5369, 0.9738, 0.3077],
        [0.1164, 0.3520, 0.8353, 0.0184]])

In [ ]:
#Find details about the tensor

print(some_t)
print(f"Datatype of tensor: {some_t.dtype}")
print(f"Shape of the tensor:{some_t.shape}")
print(f"Device of the tensor: {some_t.device}")

tensor([[0.4514, 0.9443, 0.1472, 0.3190],
        [0.8112, 0.5369, 0.9738, 0.3077],
        [0.1164, 0.3520, 0.8353, 0.0184]])
Datatype of tensor: torch.float32
Shape of the tensor:torch.Size([3, 4])
Device of the tensor: cpu


from __future__ import division
### Manipulating Tensors - Tensor Operations

Tensor operations include                 
1.Addition                               
2.Subtraction                             
3.Multiplication (element wise)           
4.Division                              
5.Matrix multiplication                   

In [ ]:
# Create a tensor
t = torch.tensor([1,2,5])
t + 10

tensor([11, 12, 15])

In [ ]:
# Multiply
t*10

tensor([10, 20, 30])

In [ ]:
#Division
t/2

tensor([0.5000, 1.0000, 1.5000])

In [ ]:
#Subtract
t-10

tensor([-9, -8, -7])

In [ ]:
#Try out pytorch inbuilt functions
torch.mul(t,10)

tensor([10, 20, 30])

In [ ]:
torch.add(t, 10)

tensor([11, 12, 13])

### Matrix maultiplication - two main ways in neural networks and deep learning

1.  Element wise multiplication                                          
2. Matrix multiplication (dot product)

Mathisfun website for dot product example

In [ ]:
#Element wise multiplacation
el_wise = t*t
el_wise

tensor([ 1,  4, 25])

In [ ]:
#Matrix multiplication
%%time
torch.matmul(t,t)

CPU times: user 0 ns, sys: 991 µs, total: 991 µs
Wall time: 809 µs


tensor(30)

In [ ]:
%%time
value = 0
for i in range(len(t)):
  value +=t[i]*t[i]

print(value)



tensor(30)
CPU times: user 2.31 ms, sys: 38 µs, total: 2.35 ms
Wall time: 3.38 ms


### Shape errors - one of the main errors in matrix multiplication
1. Inner dimesions must match                                                 
* '(3, 2) @ (3, 2)' will not work                                             
* '(2, 3) @ (3, 2)' will work                                                 
* '(3, 2) @ (2, 3)' will work                
* '@' is a matrix multiplication operator - but better to use 'matmul'
* The resulting matrix has the shape of outer dimensions:
* (2, 3) @ (3, 2) --> (2, 2)
* (3, 2) @ (2, 3) --> (3, 3)

In [ ]:
t @ t

tensor(14)

In [ ]:
#torch.matmul(torch.rand(3,2),torch.rand(3,2)) #gives an error - shape error

In [ ]:
torch.matmul(torch.rand(2,3),torch.rand(3,2)) # output --> (2,2)

tensor([[0.8008, 0.9970],
        [0.9391, 1.1942]])

In [ ]:
torch.matmul(torch.rand(3,2),torch.rand(2,3)) # output --> (3,3)

tensor([[0.5704, 0.4437, 0.5375],
        [0.3857, 0.4809, 0.5843],
        [0.5095, 0.2725, 0.3290]])

### Decoding shape errors

In [ ]:
# Shapes for mat multiplication

t_A = torch.tensor([[1,2],[3,4],[5,6]])
t_B = torch.tensor([[6,7],[8,9],[10,11]])

#### If we multiply the above, this will def give a shape error as they are both (3,2) shape
#### Hence, we will transpose one matrix - to fix tensor shape isses, the transpose switches the axes or dimensions of a given tensor

In [ ]:
#Transposing t_B

t_B.T, t_B.T.shape

(tensor([[ 6,  8, 10],
         [ 7,  9, 11]]),
 torch.Size([2, 3]))

In [ ]:
# the matrix multiplication opratinon works when tensor_B is transposed

torch.matmul(t_A, t_B.T)

tensor([[ 20,  26,  32],
        [ 46,  60,  74],
        [ 72,  94, 116]])

### Finding min, max, mean, sum etc (Tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [ ]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [ ]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [ ]:
#Mean does not work with int64 dtype hence change it to float
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
# Sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Positional min and max

In [ ]:
x.argmin() #the position of the min tensor - returns an index

tensor(0)

In [ ]:
x[0],x.argmax()

(tensor(1), tensor(9))

In [ ]:
x[9]

tensor(91)

### Reshaping, stacking, squeezing and unsqueezing Tensor
* Reshapeing - reshapes an input tensor to a defined shape                   
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combining multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions from a torch.tensor             
* Unsqueeze - adds a '1' dimension to a target torch.tensor              
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#Add an extra dimension
x_reshp = x.reshape(1,9)
x_reshp, x_reshp.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshp = x.reshape(9,1)
x_reshp, x_reshp.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
y = torch.arange(1.,11.)
y, y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
y_reshp = y.reshape(2,5)
y_reshp, y_reshp.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
y_reshp = y.reshape(5,2)
y_reshp, y_reshp.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [ ]:
# Change the view - below z shares the same memory as x
z = x.view(9,1)
z,z.shape


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# If you change z , you change x as well - share memory

z[:, 0]= 2
z,x

(tensor([[2.],
         [2.],
         [2.],
         [2.],
         [2.],
         [2.],
         [2.],
         [2.],
         [2.]]),
 tensor([2., 2., 2., 2., 2., 2., 2., 2., 2.]))

In [ ]:
# Stack tensors on top of each other
y_stack = torch.stack([y,y],dim=1)
y_stack, y_stack.shape


(tensor([[ 1.,  1.],
         [ 2.,  2.],
         [ 3.,  3.],
         [ 4.,  4.],
         [ 5.,  5.],
         [ 6.,  6.],
         [ 7.,  7.],
         [ 8.,  8.],
         [ 9.,  9.],
         [10., 10.]]),
 torch.Size([10, 2]))


### torch.squeeze - Returns a tensor with all specified dimensions of input of size 1 removed.

For example, if input is of shape:
(
A
×
1
×
B
×
C
×
1
×
D
)
(A×1×B×C×1×D)
 then the input.squeeze() will be of shape:
(
A
×
B
×
C
×
D
)
(A×B×C×D)
.



In [ ]:
x = torch.zeros(2, 1, 2, 1, 2)
x, x.size()

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [ ]:
y = torch.squeeze(x)
y,y.size()

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [ ]:
y = torch.squeeze(x, (1,2,3))
y.size(),y

(torch.Size([2, 2, 2]),
 tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]))

In [ ]:
n = torch.arange(1,7)
n

tensor([1, 2, 3, 4, 5, 6])

In [ ]:
n.reshape(2,3)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
t = n.squeeze(0)
t,t.size()

(tensor([1, 2, 3, 4, 5, 6]), torch.Size([6]))

In [ ]:
n.reshape(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
m = n.squeeze(0)
m

tensor([1, 2, 3, 4, 5, 6])

In [ ]:
#torch.unsqueeze() = adds a single dimension to a target tensor at a specific dim
print(n)
n_unsqueezed = n.unsqueeze(dim=1)

print(n_unsqueezed)

tensor([1, 2, 3, 4, 5, 6])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [ ]:
#torch.permute = rearranges the the dimensions of a target tensor in a specified order
#It means permute can alter the shape property of your tensor
x_orig=torch.rand(size=(1,2,3)) #[height,width,colour_channels]

#permute the orig tensor to rearrange the axis (or dim) order
x_permuted = x_orig.permute(2,0,1) #shifts dim 0->1, 1->2, 2->0
print(f"oiginal x shape: {x_orig.shape}")
print(f"permute x:{x_permuted.shape}") #[colour_channels, height,width]

oiginal x shape: torch.Size([1, 2, 3])
permute x:torch.Size([3, 1, 2])


In [ ]:
x_orig[0,0] = 10000
x_permuted[0,0]
x_orig,x_permuted

(tensor([[[10000., 10000., 10000.],
          [10000., 10000., 10000.]]]),
 tensor([[[10000., 10000.]],
 
         [[10000., 10000.]],
 
         [[10000., 10000.]]]))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexinf with NumPy

In [ ]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#Lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#Lets index on middle bracket dim=1
print(x[0][0])
print(x[0][1])

tensor([1, 2, 3])
tensor([4, 5, 6])


In [ ]:
#Lets index on the most inner bracket dim = 2

x[0][1][1]

tensor(5)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
#you can also use ":" to select a target dimension

x[0,1:,]

tensor([[4, 5, 6],
        [7, 8, 9]])

In [ ]:
#Get all values of 0th and 1st dim but only index 1 of 2nd dim

x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of 0 dim but only 1 index value of 1st and 2nd dim

print(x[:,1,1])
print(x[0,1,1])

tensor([5])
tensor(5)


In [ ]:
#Get index 0 of 0th and 1st dimension and all values of 2nd dimension

x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# index on x to return 9
print(x[0,2,2])

#Index on x to return [3,6,9]
print(x[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensors and NumPy

NumPy is a popular scientific python numerical computing library
And bcoz of this PyTorch has functionality to interact with it

* Data in NumPy, want in PyTorch tensor - 'torch.from_numpy(ndarray)'

* PyTorch tensor -> NumPy -> torch.Tensor.numpy()

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #Note: when converting from numpy to torch tensor, pytorch reflects numpy's default data type unless specified otherwise
array,tensor

#the default datatype of pytorch is float32 while that of numpy is float64

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
# Change the value of array, what will this do to 'tensor'?
array = array+1
array,tensor #they dont have shared memory

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor # the numpy array will now have default datatype of torch tensor - float32

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#Change the tensor - what happens to numpy tensor ?

tensor = tensor*2
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Check out this tutorial for more on numpy, tensor functions - https://docs.pytorch.org/tutorials/beginner/examples_tensor/polynomial_numpy.html

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`Start with random numbers -> tensor operations -> update random numbers to
try and make them better representations of the data -> again -> again -> again`

To reduce the radomness in neural networks / pyTorch - we introduce the concept of `random seed`

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
import torch

# Create two random tensors

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2186, 0.1521, 0.5133, 0.7129],
        [0.6291, 0.7650, 0.3689, 0.6826],
        [0.5085, 0.8371, 0.2830, 0.9748]])
tensor([[0.3479, 0.6251, 0.5451, 0.4939],
        [0.9759, 0.6016, 0.1647, 0.9338],
        [0.3972, 0.0254, 0.0796, 0.9780]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_sensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_sensor_D = torch.rand(3,4)

print(random_sensor_C)
print(random_sensor_D)
print(random_sensor_D == random_sensor_C)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch Objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers

### 1. Getting a GPU - colab has free GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade to colab pro as well)
2. Use your own GPU - takes a lil bit of setup - requires the investment of purchasing a GPU
https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use Cloud computing - GCP(Google cloud platform), AWS, AZURE - these allow you to rent computers on the cloud and access them
For 2, 3 PyTorch +GPU drivers (CUDA) takes a little bit of setting up, to do this refer to PyTorch setup documentation.

https://pytorch.org/get-started/locally/

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### 2. Check for GPU access in PyTorch

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

Since, PyTorch is capable of running code in GPU or CPU - better to setup device agnostic code that is - run in cuda (GPU) if available or run on CPU - Check this - https://docs.pytorch.org/docs/stable/notes/cuda.html#best-practices

In [ ]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
#Count number of devices
torch.cuda.device_count()

0

## 3. Putting tensors and models on the GPU

The reason we want tour tensors/ models on the GPU is because using a GPUresults in faster computations.

In [ ]:
# Create a tensor on the CPU
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
(print(tensor, tensor.device)) # CPU is the default runner

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU if available

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [ ]:
### Moving tensor back to the CPU

#If tensor is on GPU, cant transform it to NumPy
#tensor_on_gpu.numpy() ## --> will raise an error

In [ ]:
# To fix the GPU tensor with NumPy isseu, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3])

PyTorch has functionaly to work on multiple gpus as well

In [ ]:
## Exercises & Extra-curriculum